package handler

import (
	"github.com/google/wire"
	httpHandler "github.com/nori-plugins/authentication/internal/handler/http"
	"github.com/nori-plugins/authentication/internal/handler/http/administrator"
	"github.com/nori-plugins/authentication/internal/handler/http/authentication"
	"github.com/nori-plugins/authentication/internal/handler/http/mfa_recovery_code"
	"github.com/nori-plugins/authentication/internal/handler/http/mfa_totp"
	"github.com/nori-plugins/authentication/internal/handler/http/reset_password"
	"github.com/nori-plugins/authentication/internal/handler/http/settings"
	"github.com/nori-plugins/authentication/internal/handler/http/social_provider"
)

var HandlerSet = wire.NewSet(
	wire.Struct(new(httpHandler.Handler),
		"R",
		"AdminHandler",
		"AuthenticationHandler",
		"MfaRecoveryCodeHandler",
		"MfaTotpHandler",
		"ResetPasswordHandler",
		"SettingsHandler",
		"SocialProviderHandler",
		"SocialProviderService",
		"GothProviderHelper",
	),
	wire.Struct(new(administrator.Params),
		"UserService",
		"CookieHelper",
		"ErrorHelper",
		"Logger"),
	administrator.New,
	wire.Struct(new(authentication.Params),
		"AuthenticationService",
		"SessionService",
		"SocialProviderService",
		"CookieHelper",
		"ErrorHelper",
		"Config",
		"Logger"),
	authentication.New,
	wire.Struct(new(mfa_recovery_code.Params),
		"MfaRecoveryCodeService",
		"CookieHelper",
		"ErrorHelper",
		"Logger"),
	mfa_recovery_code.New,
	wire.Struct(new(mfa_totp.Params),
		"MfaTotpService",
		"CookieHelper",
		"ErrorHelper",
		"Logger"),
	mfa_totp.New,
	wire.Struct(new(reset_password.Params),
		"ResetPasswordService",
		"ErrorHelper",
		"Logger"),
	reset_password.New,
	wire.Struct(new(settings.Params),
		"SettingsService",
		"CookieHelper",
		"ErrorHelper",
		"Logger",
	),
	settings.New,
	wire.Struct(new(social_provider.Params),
		"SocialProviderService",
		"CookieHelper",
		"ErrorHelper",
		"Logger"),
	social_provider.New,
)
