---
openapi: 3.0.0
info:
  title: Nori Authentication
  license:
    name: Apache 2.0
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /auth/social/{social_provider}:
    get:
      parameters:
      - name: social_provider
        in: path
        description: social_provider
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/social/{social_provider}/callback:
    post:
      parameters:
      - name: social_provider
        in: path
        description: social_provider
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: authorization_code
        in: cookie
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSocialResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: UnauthorizedError
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/social/{social_provider}/logout:
    get:
      parameters:
      - name: access_token
        in: cookie
        description: access token from social provider
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: social_provider
        in: path
        description: social_provider
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: User signed out from social provider
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/mfa/recovery_codes/download:
    get:
      summary: download recovery codes
      operationId: recoveryCodes
      parameters:
      - name: user_id
        in: query
        description: id of user
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: ssid
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A file with recovery codes
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: UnauthorizedError
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/password:
    post:
      summary: change actual password
      parameters:
      - name: ssid
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordSetRequest'
            encoding:
              passwordOld:
                style: form
                allowReserved: true
              passwordNew:
                style: form
                allowReserved: true
        required: true
      responses:
        "200":
          description: Ok
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/password/restore:
    get:
      summary: check token for timeout
      operationId: restorePasswordCheckToken
      parameters:
      - name: ssid
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: save password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestorePasswordSetRequest'
            encoding:
              password:
                style: form
                allowReserved: true
        required: true
      responses:
        "200":
          description: Ok
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: receive token to email
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestorePasswordRequest'
            encoding:
              email:
                style: form
                allowReserved: true
        required: true
      responses:
        "200":
          description: Ok
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/signin:
    post:
      summary: authentication start user session
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
            encoding:
              email:
                style: form
                allowReserved: true
              password:
                style: form
                allowReserved: true
        required: true
      responses:
        "200":
          description: User signed in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/signout:
    get:
      summary: send token to logout
      operationId: signOut
      parameters:
      - name: ssid
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: User signed out
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/signup:
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
            encoding:
              login:
                style: form
                allowReserved: true
              password:
                style: form
                allowReserved: true
        required: true
      responses:
        "201":
          description: User's account created
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/signin/mfa:
    put:
      summary: enter authentication code in second step of two-factor authentication
      parameters:
      - name: token
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Code'
        required: true
      responses:
        "200":
          description: Ok
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: UnauthorizedError
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/settings/mfa:
    get:
      summary: receive mfa status
      operationId: mfaStatus
      parameters:
      - name: ssid
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mfa'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: UnauthorizedError
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/settings/mfa/disable:
    post:
      summary: turn off mfa
      parameters:
      - name: ssid
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: UnauthorizedError
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/settings/mfa/recovery_codes:
    get:
      summary: get generated recovery codes
      parameters:
      - name: ssid
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecoveryCodes'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: UnauthorizedError
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/settings/mfa/verify:
    get:
      summary: get generated secret from backend, login and issuer
      operationId: mfaSecret
      parameters:
      - name: ssid
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataForQRCode'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: UnauthorizedError
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/settings/mfa/enable:
    post:
      summary: enter six-digit code from app or sms and turn on mfa
      parameters:
      - name: ssid
        in: cookie
        description: user session id
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Code'
        required: true
      responses:
        "200":
          description: Ok
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: UnauthorizedError
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AuthSocialResponse:
      required:
      - accessToken
      - refreshToken
      - tokenID
      - tokenType
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        tokenID:
          type: string
        tokenType:
          type: string
    RecoveryCodes:
      type: array
      items:
        type: string
    RestorePasswordRequest:
      required:
      - actionCaptcha
      - login
      - tokenCaptcha
      type: object
      properties:
        login:
          type: string
        tokenCaptcha:
          type: string
        actionCaptcha:
          type: string
    RestorePasswordSetRequest:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    PasswordSetRequest:
      required:
      - passwordNew
      - passwordOld
      type: object
      properties:
        email:
          type: string
        token:
          type: string
        password:
          type: string
    SecretRequest:
      required:
      - secret
      type: object
      properties:
        secret:
          type: string
    SignInRequest:
      required:
      - login
      - password
      type: object
      properties:
        login:
          type: string
        password:
          type: string
    SignInResponse:
      required:
      - login
      - token
      type: object
      properties:
        token:
          type: string
        login:
          type: string
    SignUpRequest:
      required:
      - actionCaptcha
      - login
      - password
      - tokenCaptcha
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        tokenCaptcha:
          type: string
        actionCaptcha:
          type: string
    Mfa:
      required:
      - status
      type: object
      properties:
        status:
          type: boolean
    DataForQRCode:
      required:
      - issuer
      - login
      - secret
      type: object
      properties:
        login:
          type: string
        issuer:
          type: string
        secret:
          type: string
    Code:
      required:
      - code
      type: object
      properties:
        code:
          type: string
    Error:
      required:
      - code
      - errors
      type: object
      properties:
        code:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error_errors'
    Error_errors:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
